version: '3.5'

services:
  scala:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "sbt run"
    volumes:
      - .:/root
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "8306:3306"
volumes:
  db-data:
